name: Deploy to server

on: push

jobs:
  first-jobs:
    name: Tutorial de Github Actions
    runs-on: ubuntu-latest

    outputs:
      salida: ${{ steps.step_1.outputs.my_variable }}

    steps:
      - name: Working dir
        id: step_1
        run: echo "my_variable=Hola Mundo" >> $GITHUB_OUTPUT

      - name: Obtener Mensaje
        run: echo "${{ steps.step_1.outputs.my_variable }}"
  
  second-jobs:
    needs: first-jobs
    runs-on: ubuntu-latest

    env:
      SALIDA: ${{ needs.first-jobs.outputs.salida }}

    steps:
      - name: Hola Mundo
        run: echo "$SALIDA"